# Generated by Django 4.0.2 on 2022-02-10 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(upload_to=None)),
                ('last_changed', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
