# Generated by Django 4.0.2 on 2022-02-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='note',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
