# Generated by Django 4.0.2 on 2022-02-24 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_account_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_changed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
