# Generated by Django 4.0.1 on 2022-02-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_account_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='slug',
        ),
        migrations.AlterField(
            model_name='account',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
