# Generated by Django 4.0.1 on 2022-02-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_account_slug_alter_account_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='thumbnail',
        ),
    ]
