# Generated by Django 4.0.2 on 2022-02-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_account_last_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_changed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
