# Generated by Django 4.0.2 on 2022-02-24 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_account_last_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='note',
            new_name='description',
        ),
    ]
