# Generated by Django 4.0.2 on 2022-02-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_rename_note_account_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
